config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    resources :mylinks
    resources :articles
    resources :categories
    resources :category_relations    
    root "articles#index"
    #get '*path' => redirect('/')
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :article_tag
    has_many :category, through: :article_tag
    def self.categories_under_article( cua_input_id )
        cua_api = Article.find( cua_input_id ).category_ids
        return Category.select( :id , :tag_name ).where( id: cua_api )
    end
    def self.change_article_categories( cac_article_id , cac_categories_input_array )
        new_array = []
        
        if ( cac_categories_input_array != nil )
            cac_categories_input_array.each do |i|
                new_array.push( i.to_i )
            end
        end

        Article.find(cac_article_id).category_ids = new_array
        return new_array
    end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_tag
    has_many :article, through: :article_tag
    def self.articles_under_tag( aut_input_ids )
        return Article.select( :id , :title ).where( id: aut_input_ids )
    end
end

app/models/mylink.rb
class Mylink < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable :omniauthable, and :registerable,
  devise :database_authenticatable,  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

    # R for CRUD
    def index
        @articles = Article.order(id: :desc).paginate(:page => params[:page], :per_page => 10 )
        respond_to do |format|
            format.html { render :index }
            format.atom
        end
    end
    def show
        @article = Article.find_by_id(params[:id])
        @html_title = @article.title
        @markdown = Redcarpet::Markdown.new( Redcarpet::Render::HTML.new(filter_html: false) , )
        #@article.title
        # If article does not exist, return 404
        raise ActionController::RoutingError.new('Not Found') if @article.blank?
    end

    # C for CRUD
    def new
        @article = Article.new
    end
    def create
        Article.create( art_params )
        redirect_to article_path( Article.last[:id] )
    end

    # U for CRUD
    def edit
        @article = Article.find(params[:id])
    end
    def update
        @article = Article.find(params[:id])
        @article.update_attributes(art_params)
        redirect_to article_path(@article)
    end

    # D for CRUD
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    def not_found
        # 404
        raise ActionController::RoutingError.new('Not Found')
    end

    before_action :check_for_cancel, :only => [:create, :update]
    def check_for_cancel
        if params[:commit] == "Cancel"
            redirect_to articles_path
        end
    end

    private
    def art_params
        params.require(:article).permit(:title, :context)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
    def new
    end
    def create
        Category.create( atag_params )
        redirect_to categories_path
    end

    def index
        @html_title = "標籤"
        @new_cata = Category.new
        tags = Category.all
        respond_to do |format|
            format.json { render json: tags }
            format.html { render :index }  
        end
    end
    def show
        tagged_articles = Category.articles_under_tag( Category.find( params[:id] ).article_ids )
        render json: tagged_articles
    end

    def edit
        @article = Category.find(params[:id])
    end
    def update
        @article = Category.find(params[:id])
        @article.update_attributes(art_params)
        redirect_to categories_path
    end

    def destroy
        article_pending_del = Category.find(params[:id])
        article_pending_del.destroy
        redirect_to categories_path
    end

    private
    def atag_params
        params.require(:category).permit(:tag_name)
    end
end

app/controllers/category_relations_controller.rb
class CategoryRelationsController < ApplicationController
    # Pure JSONs
    # Do such things:
    # Article.find(1).category_ids => [1, 4, 5, 6] # Show
    #
    # Article.find(1).category_ids = [ 1 , 5 , 6 ] # update
    # Article.find(2).category_ids = [ 4 , 5 ]
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
    def show
        outputs = Article.find( params[:id] ).category_ids
        #Article.categories_under_article(params[:id])
        render json: outputs
    end
    def update
        new_cate = Article.change_article_categories( params[:id] , params[:cate_id] )
        render json: new_cate
    end
end

app/controllers/mylinks_controller.rb
class MylinksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  # C
  def new
    @link = Mylink.new
    render layout: false
  end
  def create
    Mylink.create( link_params )
    redirect_to mylinks_path
  end

  # R
  def index
    @html_title = "連結"
    @links = Mylink.order(id: :asc)
  end

  # U
  def edit
    @link = Mylink.find(params[:id])
    render layout: false
  end
  def update
    @link = Mylink.find(params[:id])
    @link.update_attributes(link_params)
    redirect_to mylinks_path
  end

  # D
  def destroy
    @link = Mylink.find(params[:id])
    @link.destroy
    redirect_to mylinks_path
  end

  # params
  private
  def link_params
    params.require(:mylink).permit(:site, :name, :intro, :group)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sns_link( sns_type )
        def sns_type_switch( sts_input )
            case sts_input
            when "firefox"
                return "https://developer.mozilla.org/zh-TW/profiles/"
            when "github"
                return "https://www.github.com/"
            when "codepen"
                return "https://codepen.io/"
            else
                return root_path
            end
        end
        account_name = "iigmir"
        website = sns_type_switch( sns_type ) + account_name

        link_to website, target: "_blank", title: sns_type do
            fa_icon sns_type
        end
    end

    def login_and_out()
        if user_signed_in?
            link_to destroy_user_session_path, method: :delete do
                fa_icon "sign-out"
            end
        else
            link_to new_user_session_path do
                fa_icon "sign-in"
            end
        end
    end

    def devise_message()
        devise_msg_class = ""
        devise_msg_text = nil
        
        if notice
            devise_msg_class = "message"
            devise_msg_text = notice
        end
        if alert
            devise_msg_class = "message error"
            devise_msg_text = alert
        end

        content_tag(:p, devise_msg_text, class: devise_msg_class)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_relations_helper.rb
module CategoryRelationsHelper
end

app/helpers/mylinks_helper.rb
module MylinksHelper
end

app/views/articles/_form.html.erb
<%= form_for @article , html:({class:"form"}) do |m| %>
    <main>
        <div class="form-item">
            <%= m.label :title , "標題" %>
            <%= m.text_field :title %>
        </div>
        <div class="form-item">
            <%= m.label :context , "內文" %>
            <%= m.text_area :context %>
        </div>
        <div class="form-item">
            <%= m.submit "送出文章" , class: "button" %>
            <%= link_to '取消', @article , class: "secondary outline button" %>
        </div>
    </main>
<% end %>

<%= content_for :js_plugins do %>
<script>
var simplemde = new SimpleMDE({
    element: document.getElementById("article_context"),
    toolbar: ["preview","guide","|",
    "bold", "italic", "heading", "|",
    "link", "code", "quote", "strikethrough", "|",
    "unordered-list","ordered-list","table", "|",
    "horizontal-rule","clean-block"],
    spellChecker: false,
    status: false
});
</script>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center">編輯文章</h1><%= render "form" %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
    <p class="text-center">你好，請問想<a class="text-center" href="/articles/new">寫新文章</a>嗎？</p>
<% end %>

<main>
    <ul style="list-style:none;">
    <% @articles.each do |a| %>
    <li>
        <h2> <%= link_to a.title, article_path(a.id) ,method: :get  %> </h2>
        <span> 建立：<%= a.created_at %><br/> 最後更新：<%= a.updated_at %> </span>
    </li>
    <% end %>
    </ul>
    <div class="text-center"> <%= will_paginate @articles %> </div>
</main>

app/views/articles/new.html.erb
<h1 class="text-center">新增文章</h1><%= render "form" %>

app/views/articles/show.html.erb
<% a = @article %>
<main>
    <article>
        <div class="article_info breakline">
            <h2> <%= a.title %> </h2>
            <p style="padding-left:1rem;">
                <b> Created:<%= a.created_at %>, Last updated: <%= a.updated_at %> </b> <br />
                <% if user_signed_in? %>
                    請問想<a class="text-center" href="/articles/new">寫新文章</a>、<%= link_to '編輯這篇文章',  edit_article_url(a.id) %>、還是想<%= link_to '刪除這篇文章', article_path(a.id), method: :delete, class:"error", data: {confirm: '注意，這篇文章會永遠消失！你還是要刪除嗎？\n（注意：在刪除文章前，必須刪除目錄標籤！）'} %>呢？
                <% end %>
            </p>
        </div>
        <div class="article_context breakline">
            <%= raw( @markdown.render( a.context ) ) %>
        </div>
        
        <div class="category" data-ajax-request-id="<%= params[:id] %>">
            <div class="help">
                <h3>這篇文章屬於以下目錄：</h3>
                <div class="label_view"></div>
                <% if user_signed_in? %>
                <button data-component="modal" data-target="#select_category">編輯</button>
                <% end %>
            </div>
            <%= render "layouts/ajaxfail", costom_classes: "show" %>
        </div>
    </article>
</main>

<% if user_signed_in? %>
<div id="select_category" class="modal-box hide">
    <div class="modal">
        <div class="modal-header">分類後台</div>
        <div class="modal-body">
            <div class="hide warning message">
                <p>注意：分類尚未儲存，請點選下方的「儲存分類」按鈕，才能儲存當前分類。</p>
            </div>
            <div class="form-item">
                <div class="append">
                    <select></select>
                    <button class="add button">新增</button>
                </div>
            </div>
            <ul class="label_view"></ul>
            <button class="save" type="button">儲存分類</button>
        </div>
    </div>
</div>
<% end %>

<%= content_for :js_plugins do %>
    <%= javascript_include_tag "article_form" %>
<% end %>

app/views/categories/index.html.erb
<main>
    <% if user_signed_in? %>
        <div id="new_tag_form" class="w60">
            <%= form_for @new_cata do |t| %>
                <div class="append w50">
                    <%= t.text_field :tag_name , required: true  %>
                    <%= t.submit "新增分類" %>
                </div>
            <% end %>
        </div>
    <% end %>
    <div id="tags_breakline"></div>
    <div id="render_view"></div>
    <div class="ajax-inline-waiting"> 等待載入中... </div>
    <%= render "layouts/ajaxfail", costom_classes: "index" %>
</main>

<div id="articles_modal" class="modal-box hide">
    <div class="modal">
        <span class="close"></span>
        <div class="modal-header clicked_value">
        </div>
        <div class="modal-body">
            <p class="help_text"></p>
            <ul class="render_texts"></ul>
            <%= render "layouts/ajaxfail", costom_classes: "show" %>
            <% if user_signed_in? %>
            <a href="#" class="delete warning button" rel="nofollow" data-method="delete"
            data-confirm="你確定要刪除嗎？這個動作無法復原！">
                刪除此分類
            </a>
            <% end %>
        </div>
    </div>
</div>

<%= content_for :js_plugins do %>
    <%= javascript_include_tag "article_tags" %>
<% end %>

app/views/layouts/_ajaxfail.html.erb
<div class="<%= costom_classes %> ajaxfail hide">: - ( <br />看起來頁面載入失敗了噢，我會去修。 <br />如果有興趣也可以查查瀏覽器工具，看發生了什麼事。</div>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="l-side">
        <h1>
        <%=
            link_to root_url do
                image_tag("rails.png",alt:"露比的銳思",title:"露比的銳思")
            end
        %>
        </h1>
    </div>
    <div class="r-side">
        <div>
            <%= sns_link( "firefox" ) %>
            <%= sns_link( "github" ) %>
            <%= sns_link( "codepen" ) %>
            <%= link_to mylinks_path do %>
                <%= fa_icon "link" %>
            <% end %>
            <%= link_to categories_path do %>
                <%= fa_icon "tags" %>
            <% end %>
            <%= link_to root_url + "articles.atom" do %>
                <%= fa_icon "rss" %>
            <% end %>
            <%= login_and_out() %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-hant">
    <head>
        <meta charset="utf-8" />
        <title><%= @html_title ? "露比的銳思："+@html_title : "露比的銳思" %></title>
        <%= favicon_link_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="希望黑澤露比也看得懂我在寫啥" />
        <meta name="keywords" content="Ruby on Rails,Web development,Front-end development" />
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag 'application', media: 'all' %>
        <link rel="stylesheet" href="assets/simplemde.min.css">
        <%= stylesheet_link_tag params[:controller] %>
    </head>
    <body id="<%= controller.controller_name %>_<%= controller.action_name %>">
        <%= render "layouts/navbar" %>
        <%= devise_message() %>
        <%= yield %>
        <div class="hide ajax-waiting">
            <div class="draws">
                <p>資料處理中…</p>
            </div>
        </div>
        <%= javascript_include_tag 'application', controller_name %>
        <%= javascript_include_tag "simplemde.min" %>
        <%= yield(:js_plugins) %>
        <%= yield(:js_custom) %>
    </body>
</html>

app/views/mylinks/_form.html.erb
<div class="row align-center"><div class="col col-12">
<%= form_for @link do |l| %>
    <table>
        <tr>
            <td> <%= l.label :name,"Site name" %> </td>
            <td> <%= l.text_field :name, :required => true %> </td>
        </tr>
        <tr>
            <td> <%= l.label :site,"Site address" %> </td>
            <td> <%= l.text_field :site, :required => true, :value => controller.action_name == "edit" ? @link.site : "https://" %> </td>
        </tr>
        <tr>
            <td> <%= l.label :intro,"Site info" %> </td>
            <td> <%= l.text_field :intro, :required => true %> </td>
        </tr>
        <tr>
            <td> <%= l.label :group,"Which group this site should be?" %> </td>
            <td> <%= l.text_field :group, :required => true %> </td>
        </tr>
        <tr id="highrisk">
            <td> <%= l.submit "Submit Link" %> </td>
            <td> <%= link_to 'Cancel', mylinks_path %> </td>
        </tr>
    </table>
<% end %>
</div></div>

app/views/mylinks/edit.html.erb
<h1 class="text-center">Edit link</h1>
<%= render "form" %>

app/views/mylinks/index.html.erb
<p class="text-center">
    <% if user_signed_in? %>
        Hello there <strong><%= current_user.email %></strong>.
        Want to add <%= link_to "new link", "#", 
        :data => { :component => "modal", :target => "#my-modal", :user_action => new_mylink_path } %>,

        or <%= link_to "logout", destroy_user_session_path, method: :delete %> ?
    <% else %>
        Hello there guest,
        want to <%= link_to "login", new_user_session_path %>?
    <% end %>
</p>
<div class="row align-center">
    <div class="col col-6">
        <p class="text-center">這裡會條列一些有趣的網站。</p>
    </div>
</div>
<div class="row align-center">
    <div class="col col-6">
        <ul>
            <% @links.each do |l| %>
                <li class="crud_mylink"> 
                    <% if user_signed_in? %>
                        <%= link_to "#", :data => { :component => "modal", :target => "#my-modal", :user_action => edit_mylink_path(l.id) } do %>
                            <%= fa_icon "pencil" %>
                        <% end %>
                        <%= link_to mylink_path(l.id), method: :delete , data: { confirm: 'Are you sure? THIS LINK WILL DISAPPEAR FOREVER!'} do %>
                            <%= fa_icon "times" %>
                        <% end %>
                    <% end %>
                    <%= link_to l.name , l.site , target: "_blank" %> : <%= l.intro %>
                </li>
            <% end %>
        </ul>
    </div>
</div>
<div id="my-modal" class="modal-box hide">
    <div class="modal">
        <span class="close"></span>
        <div class="modal-header">編輯連結</div>
        <div class="modal-body">等待中...</div>
    </div>
</div>
<%= content_for :js_custom do %>
<script>
document.querySelectorAll('a[data-target="#my-modal"]').forEach(element =>
{
    element.addEventListener( "click" , (e) =>
    {
        let modal_body = document.querySelector("#my-modal .modal-body");
        let ajax_api = e.currentTarget.dataset.userAction;
        let request = new XMLHttpRequest();
        request.open( "GET" , ajax_api , true);
        request.onload = () =>
        {
            if (request.status >= 200 && request.status < 400)
            {
                modal_body.innerHTML = request.responseText;
            }
            else
            {   // We reached our target server, but it returned an error
                modal_body.innerHTML = `<p> Error encounter :( </p> <p>${request.responseText}</p>`;
                console.error( request );
            }
        };
        request.onerror = () =>
        {
            // There was a connection error of some sort
            modal_body.innerHTML = `<p> Error encounter :( </p> <p>${request.responseText}</p>`;
            console.error( request );
        };
        request.send();
    }, false );
});
</script>
<% end %>

app/views/mylinks/new.html.erb
<h1 class="text-center">Add link</h1>
<%= render "form" %>